name: Deploy AdmireSoftech Backend

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy to production
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Starting deployment..."

            cd /home/ubuntu/AdmireSoftech_B

            echo "Pulling latest changes from the repository..."
            git fetch origin main

            echo "Resetting working directory to match the latest commit..."
            git reset --hard origin/main

            echo "Installing production dependencies..."
            npm ci --omit=dev

            echo "Reloading the PM2 process..."
            pm2 reload api.as

            echo "Checking the status of the PM2 process..."
            pm2 status api.as

            echo "Deployment completed successfully!"